#!/bin/sh
exec ./unshare-chroot -d /proc "$PWD/rootfs/proc" \
	-d /sys "$PWD/rootfs/sys" \
	-d /dev "$PWD/rootfs/dev" \
	-d "$PWD" "$PWD/rootfs/build-tmp" \
	-b "$PWD/fake-bin/chown" "$PWD/rootfs/bin/chown" \
	-b "$PWD/fake-bin/chgrp" "$PWD/rootfs/bin/chgrp" \
	-m "$PWD/rootfs/" -- /bin/sh <<EOF
PATH="/build-tmp/xbps/usr/bin:/usr/bin" exec \
/build-tmp/xbps/usr/bin/xbps-reconfigure \
	-C "/build-tmp/xbps/usr/share/xbps.d" \
	"$@"
EOF
