#!/bin/sh
exec ./unshare-chroot \
-d "$PWD/rwfs/var" "$PWD/rootfs/var" \
-b "$PWD/fake-bin/chown" "/bin/chown" \
-b "$PWD/fake-bin/chgrp" "/bin/chgrp" \
-- $PWD/xbps/usr/bin/xbps-install \
	-C "$PWD/xbps/usr/share/xbps.d" \
	-c "$PWD/xbps/var/db/xbps" \
	-r "$PWD/rootfs" \
	-R "$PWD/void-packages/hostdir/binpkgs" \
	"$@"
