#!/bin/sh
PATH="/mnt/xbps/usr/bin:/usr/bin" \
exec ./unshare-chroot -d /proc "$PWD/rootfs/proc" \
	-d /sys "$PWD/rootfs/sys" \
	-d /dev "$PWD/rootfs/dev" \
	-d "$PWD" "$PWD/rootfs/mnt" \
	-d "$PWD/rwfs/var" "$PWD/rootfs/var" \
	-b "$PWD/fake-bin/chown" "$PWD/rootfs/bin/chown" \
	-b "$PWD/fake-bin/chgrp" "$PWD/rootfs/bin/chgrp" \
	-b "$PWD/fake-bin/mknod" "$PWD/rootfs/bin/mknod" \
	-m "$PWD/rootfs/" \
	-- /mnt/xbps/usr/bin/xbps-reconfigure \
		-C "/build-tmp/xbps/usr/share/xbps.d" \
		"$@"
