#!/bin/sh
exec ./unshare-chroot \
-d "$PWD/rwfs/var" "$PWD/rootfs/var" \
-- $PWD/xbps/usr/bin/xbps-query \
	-C "$PWD/xbps/usr/share/xbps.d" \
	-c "$PWD/xbps/var/db/xbps" \
	-r "$PWD/rootfs" \
	--repository="$PWD/void-packages/hostdir/binpkgs" \
	"$@"
